// .pi/extensions/overstory-guard.ts
// Generated by overstory — do not edit manually.
// Agent: coordinator | Capability: coordinator
import type { Extension } from "@mariozechner/pi-coding-agent";

const AGENT_NAME = "coordinator";
const WORKTREE_PATH = "/Users/jayminwest/Projects/os-eco/overstory";

// Native team/task tools blocked (all agents) — use ov sling for delegation.
const TEAM_BLOCKED = new Set<string>([
	"Task",
	"TeamCreate",
	"TeamDelete",
	"SendMessage",
	"TaskCreate",
	"TaskUpdate",
	"TaskList",
	"TaskGet",
	"TaskOutput",
	"TaskStop",
]);

// Interactive tools blocked (all agents) — escalate via ov mail instead.
const INTERACTIVE_BLOCKED = new Set<string>([
	"AskUserQuestion",
	"EnterPlanMode",
	"EnterWorktree",
]);

// Write tools blocked for non-implementation capabilities.
const WRITE_BLOCKED = new Set<string>([
	"Write",
	"Edit",
	"NotebookEdit",
]);

// Write-scope tools where path boundary is enforced (all agents, defense-in-depth).
const WRITE_SCOPE_TOOLS = new Set<string>(["Write", "Edit", "NotebookEdit"]);

// Safe Bash command prefixes — checked before the dangerous pattern blocklist.
const SAFE_PREFIXES = [
	"ov ",
	"overstory ",
	"bd ",
	"sd ",
	"git status",
	"git log",
	"git diff",
	"git show",
	"git blame",
	"git branch",
	"mulch ",
	"git add",
	"git commit",
	"bun test",
	"bun run lint",
	"bun run typecheck",
];

// Dangerous Bash patterns blocked for non-implementation agents.
const DANGEROUS_PATTERNS = [
	/sed\s+-i/,
	/sed\s+--in-place/,
	/echo\s+.*>/,
	/printf\s+.*>/,
	/cat\s+.*>/,
	/tee\s/,
	/\bvim\b/,
	/\bnano\b/,
	/\bvi\b/,
	/\bmv\s/,
	/\bcp\s/,
	/\brm\s/,
	/\bmkdir\s/,
	/\btouch\s/,
	/\bchmod\s/,
	/\bchown\s/,
	/>>/,
	/\bgit\s+add\b/,
	/\bgit\s+commit\b/,
	/\bgit\s+merge\b/,
	/\bgit\s+push\b/,
	/\bgit\s+reset\b/,
	/\bgit\s+checkout\b/,
	/\bgit\s+rebase\b/,
	/\bgit\s+stash\b/,
	/\bnpm\s+install\b/,
	/\bbun\s+install\b/,
	/\bbun\s+add\b/,
	/\bbun\s+-e\b/,
	/\bbun\s+--eval\b/,
	/\bnode\s+-e\b/,
	/\bnode\s+--eval\b/,
	/\bdeno\s+eval\b/,
	/\bpython3?\s+-c\b/,
	/\bperl\s+-e\b/,
	/\bruby\s+-e\b/,
];

// File-modifying Bash patterns requiring path boundary validation (implementation agents).
const FILE_MODIFYING_PATTERNS = [
	/sed\s+-i/,
	/sed\s+--in-place/,
	/echo\s+.*>/,
	/printf\s+.*>/,
	/cat\s+.*>/,
	/tee\s/,
	/\bmv\s/,
	/\bcp\s/,
	/\brm\s/,
	/\bmkdir\s/,
	/\btouch\s/,
	/\bchmod\s/,
	/\bchown\s/,
	/>>/,
	/\binstall\s/,
	/\brsync\s/,
];

export default (): Extension => ({
	tool_call: async (event) => {
		// 1. Block native team/task tools (all agents).
		if (TEAM_BLOCKED.has(event.name)) {
			return {
				type: "block",
				reason: `Overstory agents must use 'ov sling' for delegation — ${event.name} is not allowed`,
			};
		}

		// 2. Block interactive tools (all agents).
		if (INTERACTIVE_BLOCKED.has(event.name)) {
			return {
				type: "block",
				reason: `${event.name} requires human interaction — use ov mail (--type question) to escalate`,
			};
		}

		// 3. Block write tools for non-implementation capabilities.
		if (WRITE_BLOCKED.has(event.name)) {
			return {
				type: "block",
				reason: `coordinator agents cannot modify files — ${event.name} is not allowed`,
			};
		}

		// 4. Path boundary enforcement for Write/Edit/NotebookEdit (all agents).
		if (WRITE_SCOPE_TOOLS.has(event.name)) {
			const filePath = String(
				(event.input as Record<string, unknown>)?.file_path ??
				(event.input as Record<string, unknown>)?.notebook_path ??
				"",
			);
			if (filePath && !filePath.startsWith(WORKTREE_PATH + '/') && filePath !== WORKTREE_PATH) {
				return {
					type: "block",
					reason: "Path boundary violation: file is outside your assigned worktree. All writes must target files within your worktree.",
				};
			}
		}

		// 5. Bash command guards.
		if (event.name === "Bash" || event.name === "bash") {
			const cmd = String((event.input as Record<string, unknown>)?.command ?? "");

			// Universal danger guards (all agents).
			if (/\bgit\s+push\b/.test(cmd)) {
				return {
					type: "block",
					reason: "git push is blocked — use ov merge to integrate changes, push manually when ready",
				};
			}
			if (/git\s+reset\s+--hard/.test(cmd)) {
				return {
					type: "block",
					reason: "git reset --hard is not allowed — it destroys uncommitted work",
				};
			}
			const branchMatch = /git\s+checkout\s+-b\s+(\S+)/.exec(cmd);
			if (branchMatch) {
				const branch = branchMatch[1] ?? "";
				if (!branch.startsWith(`overstory/${AGENT_NAME}/`)) {
					return {
						type: "block",
						reason: `Branch must follow overstory/${AGENT_NAME}/{task-id} convention`,
					};
				}
			}

			// Non-implementation agents: whitelist safe prefixes, block dangerous patterns.
			const trimmed = cmd.trimStart();
			if (SAFE_PREFIXES.some((p) => trimmed.startsWith(p))) {
				return { type: "allow" };
			}
			if (DANGEROUS_PATTERNS.some((re) => re.test(cmd))) {
				return {
					type: "block",
					reason: "coordinator agents cannot modify files — this command is not allowed",
				};
			}
		}

		return { type: "allow" };
	},
});
